// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFqYtoX8SmNCxI42dG7s0QkRdjrycR5J0',
    appId: '1:1042225667960:web:88ea7502a2622c5f0a728d',
    messagingSenderId: '1042225667960',
    projectId: 'basecrudfl',
    authDomain: 'basecrudfl.firebaseapp.com',
    storageBucket: 'basecrudfl.appspot.com',
    measurementId: 'G-RJQZVV8RJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjeDr9betZf3ahdWpgoRWAVGYWLNWcpKo',
    appId: '1:1042225667960:android:e9a4a756f492d7ef0a728d',
    messagingSenderId: '1042225667960',
    projectId: 'basecrudfl',
    storageBucket: 'basecrudfl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsG30J6nf-Aox3DMbi8BoQS-WxncIzxqc',
    appId: '1:1042225667960:ios:f9b3b4e867f90d730a728d',
    messagingSenderId: '1042225667960',
    projectId: 'basecrudfl',
    storageBucket: 'basecrudfl.appspot.com',
    iosClientId: '1042225667960-pbfiihlonjktodi0mnjhrjogu60app19.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsG30J6nf-Aox3DMbi8BoQS-WxncIzxqc',
    appId: '1:1042225667960:ios:418214b5b8dee1720a728d',
    messagingSenderId: '1042225667960',
    projectId: 'basecrudfl',
    storageBucket: 'basecrudfl.appspot.com',
    iosClientId: '1042225667960-cgrnodk701bd267joc7cbbjl55aapn47.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFlutter.RunnerTests',
  );
}
